title: Michele Piazzai
author: Michele Piazzai
description: The University of Edinburgh
url: https://piazzai.github.io
permalink: pretty

exclude:
  - Gemfile
  - LICENSE
  - README.md
  - vendor/
  - cv/*.aux
  - cv/*.fdb_latexmk
  - cv/*.fls
  - cv/*.log
  - cv/*.out
  - cv/*.synctex.gz
  - cv/*.tex

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
