title: ComuniDados
description: "Compreender dados é uma forma de participar."
url: https://betinaschilling.github.io
author: Cheila Betina Schilling dos Santos
email: c.santos.research@gmail.com
lang: pt-BR
permalink: pretty

exclude:
  - Gemfile
  - LICENSE
  - README.md
  - vendor/
  - preview/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

navigation:
  - title: "Início"
    url: "/"
  - title: "Dossiês"
    url: "/dossies/"
  - title: "Artigos"
    url: "/artigos/"
  - title: "Investigações"
    url: "/investigacoes/"
  - title: "Manifesto"
    url: "/manifesto/"
  - title: "Sobre"
    url: "/sobre/"
