title: ComuniDados
description: "Compreender dados é uma forma de participar."
url: https://betinaschilling.github.io
author: Cheila Betina Schilling dos Santos
email: c.santos.research@gmail.com
lang: pt-BR
permalink: pretty

exclude:
  - Gemfile
  - LICENSE
  - README.md
  - docs/
  - vendor/
  - preview/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

navigation:
  - title: "Início"
    url: "/"
  - title: "Artigos"
    url: "/artigos/"
  - title: "Laboratório"
    url: "/laboratorio/"
  - title: "Manifesto"
    url: "/manifesto/"
  - title: "Sobre"
    url: "/sobre/"
