title: Michele Piazzai
author: Michele Piazzai
description: The University of Edinburgh
url: https://piazzai.github.io
permalink: pretty

exclude:
  - Gemfile
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
