title: Hacked Jekyll
description: Jekyll microtheme that looks like JSON
baseurl: /hacked-jekyll
url: https://piazzai.github.io

theme: hacked-jekyll

color_key: green-9
lowercase: keys
quotes: values

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  