title: Cheila Santos
description: Cientista de Dados
url: https://betinaschilling.github.io
author: Cheila Betina Schilling dos Santos
permalink: pretty

exclude:
  - Gemfile
  - LICENSE
  - README.md
  - vendor/
  - cv.aux
  - cv.fdb_latexmk
  - cv.fls
  - cv.log
  - cv.out
  - cv.synctex.gz
  - cv.tex

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
