title: Michele Piazzai
description: Assistant Professor and Ramón y Cajal Fellow at Carlos III University of Madrid
baseurl: ""
url: https://piazzai.github.io

theme: hacked-jekyll

color_key: green-9
lowercase: keys
quotes: values

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  