- icon: person-circle
  url: https://business.uc3m.es/en/faculty/profesor/perfil/michele-piazzai
- icon: envelope-fill
  url: mailto:michele.piazzai@uc3m.es
- icon: google-scholar
  url: https://scholar.google.com/citations?user=L3yiAMcAAAAJ
- icon: orcid
  url: https://orcid.org/0000-0001-9676-7422
- icon: clarivate
  url: https://www.webofscience.com/wos/author/record/ABH-6674-2020
- icon: scopus
  url: https://www.scopus.com/authid/detail.uri?authorId=56123810600
- icon: github
  url: https://github.com/piazzai
- icon: lichess
  url: https://lichess.org/@/piazzai
